---

- hosts: "{{ f5hosts }}"
  vars:
    provider:
      server: "{{ hostvars[inventory_hostname].ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false
      server_port: 443
      no_f5_teem: true
  gather_facts: false
  any_errors_fatal: true

  tasks:
  - name: Launch iSeries Role
    ansible.builtin.include_role:
      name: iSeries
    when: platform_type == "iSeries" 
  
  - name: Launch rSeries Role
    ansible.builtin.include_role:
      name: rSeries
    when: platform_type == "rSeries" 
