- name: Backup UCS File
  hosts: ucsBackupTargets
  connection: local
  vars:
    provider:
      server: "{{ hostvars[inventory_hostname].ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false
      server_port: 443
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: Create UCS backup directory if it does not exist
      file:
        path: "{{ ucs_dir }}"
        state: directory
    
    - name: Download a new UCS
      bigip_ucs_fetch:
        src: cs_backup.ucs
        dest: "{{ ucs_dir }}/{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}.ucs"
        provider: "{{ provider }}"
      delegate_to: localhost
    
    - name: Find all UCS files older than {{ remove_ucs_older_than_days}} days.
      find:
        paths: "{{ ucs_dir }}"
        age:  "{{ remove_ucs_older_than_days + 'd' }}" 
        recurse: yes
      register: filesOlderThanDays
      when: remove_old_ucs == True
    
    - name: Remove older than {{ remove_ucs_older_than_days}} days
      file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ filesOlderThanDays.files }}"
      when: remove_old_ucs == True