
f5hosts: "default" ## Set F5 hosts to default value when not specified at runtime. Fixes validation errors. 
username: "admin" ## Set default F5 username
password: "{{ lookup('env','BIGIP_PASSWORD') }}" ## Set f5 password from environment variable 

platform_type: rSeries ## Specifies this host group type. Possible values: iSeries, VE, rSeries.  

## iSeries physical interface definitions 
interfaces:
  - name: 8.0
    bundle: disabled

## rSeries trunk
trunks:
  - name: trunk-1
    members: 
      - 8.0
      - 9.0
    lacp_mode: active
    lacp_timeout: fast

## Vlans
vlans:
  - name: external-test
    interface: trunk-1
    tag: 2345