## rSeries physical interface definitions (non-LAG vlan interfaces)
interfaces: ## Comment out interfaces section below if you don't need to configure physical interfaces.
  - name: 3.0                          # Interface name (format: slot.port — here, slot 7, port 0)
    description: INSIDE
    bundle: disabled                  # Interface bundle mode (must be set manually before Ansible runs)
    # native_vlan:                  # VLAN assigned as native (untagged traffic). Comment out if not needed.
    trunked_vlans:                    #Type= List. VLANs allowed as tagged on this interface. Comment out if not needed.
      - 61
      - 62

## rSeries LAG (Link Aggregation Group) definitions
lags:
  - name: lag-1                     # Logical lag name (used for LACP/LAG configuration)
    members:
      - 8.0                           # List of interfaces participating in the lag
      - 9.0
    lag_type: lacp              # Set lag mode to LACP or static
    lacp_mode: passive               # Skipped if lag_type=static. LACP mode: 'passive' (waits for LACP initiation)
    lacp_timeout: fast              # Skipped if lag_type=static. LACP timeout: 'fast' = short timeout (1 second)
    native_vlan: 2346                # VLAN assigned as native (untagged on this lag). Leave empty value to skip.
    trunked_vlans:                  # Tagged VLANs allowed on this lag. Leave empty value to skip.
      - 2345

## VLANs
vlans:
  - name: external-test              # Logical name for VLAN (used as the identifier in F5 configuration)
    tag: 61                        # 802.1Q VLAN ID
  - name: internal-test
    tag: 62
  - name: external-test2              # Logical name for VLAN (used as the identifier in F5 configuration)
    tag: 2345                        # 802.1Q VLAN ID
  - name: internal-test2
    tag: 2346

## DNS Configuration
dns_servers:
  - "8.8.8.8"

dns_domains:
  - "lab.local"

## NTP Configuration
ntp_servers:
  - server: "pool.ntp.org"
    state: present

## SNMP Configuration
snmp_community:
  - name: "{{ SNMP_COMMUNITY }}"      # Encrypted SNMP community string from vault
    security_model:
      - "v2c"

snmp_mib:
  syscontact: "admin@localhost"
  syslocation: "KC"
  sysname: "{{ inventory_hostname }}"

## LLDP Configuration
lldp_config:
  enabled: true
  system_name: "{{ inventory_hostname }}"
  system_description: "Lab rSeries"
  tx_interval: 30
  tx_hold: 4
  reinitiate_delay: 2
  tx_delay: 2
  max_neighbors_per_port: 10

## System Banner Configuration
system_config:
  hostname: "{{ inventory_hostname }}"
  motd: "This system is for serious stuff only."
  login_banner: "This system is for serious stuff only."

## Name of tenant files to upload to rSeries from roles/rSeries/files/
tenant_images:
  - BIGIP-17.1.2.2-0.0.12.ALL-F5OS.qcow2.zip.bundle  # F5 BIG-IP tenant image filename (must match exactly and be present in role's files/)

## Exastive list of tenants to be provisioned on this rSeries host.
## Make sure tenant hostname and management IP to be added to inventory as child group of host.
tenants:
  - name: exampletenant
    ansible_state: present                    # Desired state of the tenant (default to 'present') or absent to remove.
    image_name: BIGIP-17.1.2.2-0.0.12.ALL-F5OS.qcow2.zip.bundle
    management_ip: 192.168.1.43
    management_prefix: 24
    management_gateway: 192.168.1.9
    vlans: 'ALL' #List vlans to be passed to tenant here as list of IDs [2345, 2346] or special keyword ALL in which case all vlans configured on this host will be passed.
    cpu_cores: 8
    memory: 29184 #min-memory = ((3.5 * 1024 * cpu_cores ) + (512))
    virtual_disk_size: 84
    running_state: deployed
