## Set HTTP API vars
ansible_user: "{{ username }}"
ansible_httpapi_password: "{{ password }}"
ansible_network_os: "f5networks.f5os.f5os"
ansible_httpapi_use_ssl: true
ansible_httpapi_use_proxy: false
ansible_httpapi_validate_certs: "{{ provider.validate_certs }}"
ansible_httpapi_port: "{{ provider.server_port }}"
