- name: Update Interface Settings
  f5networks.f5_modules.bigip_interface:
    name: "{{ item.name }}"
    bundle: "{{ item.bundle }}"
    provider: "{{ provider }}"
  delegate_to: localhost
  loop: "{{ interfaces }}"

- name: Create trunk
  f5networks.f5_modules.bigip_trunk:
    name: "{{ item.name }}"
    interfaces: "{{ item.members }}"
    lacp_enabled: "{{ item.lacp_enabled }}"
    lacp_mode: "{{ item.lacp_mode }}"
    lacp_timeout: "{{ item.lacp_timeout }}"
    provider: "{{ provider }}"
  delegate_to: localhost
  loop: "{{ trunks }}"

- name: Launch Common Role
  ansible.builtin.include_role:
    name: Common

